#+AUTHOR: Corey Smith
#+TITLE: Emacs configuration file
#+BABEL: :cache yes
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{inconsolata}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+PROPERTY: header-args :tangle yes

* Overview

Some of these functions are from https://github.com/sachac/.emacs.d/blob/gh-pages/Sacha.org .
* git initialization
There is no reason to track the init.el that is generated; by running
the following command git will not bother tracking it:

#+BEGIN_SRC sh :tangle no
git update-index --assume-unchanged init.el
#+END_SRC

If one wishes to make changes to the repo-version of init.el start
tracking again with:

#+BEGIN_SRC sh :tangle no
git update-index --no-assume-unchanged init.el
#+END_SRC

* Where to get the packages from
#+BEGIN_SRC emacs-lisp
(package-initialize)
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/")
             '("elpy" . "http://jorgenschaefer.github.io/packages/"))
(setq package-enable-at-startup nil)
#+END_SRC

* use package
#+BEGIN_SRC emacs-lisp
; This is only needed once, near the top of the file
(eval-when-compile
  ;; Following line is not needed if use-package.el is in ~/.emacs.d
  (add-to-list 'load-path "<path where use-package is installed>")
  (require 'use-package))
#+END_SRC

* emacs and skim
#+BEGIN_SRC emacs-lisp :tangle no
;; Starts the Emacs server
(server-start)
;; Auto-raise Emacs on activation
(defun raise-emacs-on-aqua() 
    (shell-command "osascript -e 'tell application \"Emacs\" to activate' &"))
(add-hook 'server-switch-hook 'raise-emacs-on-aqua)
;; The following only works with AUCTeX loaded
(require 'tex-site)
(add-hook 'TeX-mode-hook
    (lambda ()
        (add-to-list 'TeX-output-view-style
            '("^pdf$" "."
              "/Applications/Skim.app/Contents/SharedSupport/displayline %n %o %b")))
)

;; Use PDF mode by default
(setq-default TeX-PDF-mode t)
;; Make emacs aware of multi-file projects
(setq-default TeX-master nil)

#+END_SRC
* Backups

This is one of the things people usually want to change right away. By default, Emacs saves backup files in the current directory. These are the files ending in =~= that are cluttering up your directory lists. The following code stashes them all in =~/.emacs.d/backups=, where I can find them with =C-x C-f= (=find-file=) if I really need to.

#+BEGIN_SRC emacs-lisp :tangle yes
 (setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
#+END_SRC

Disk space is cheap. Save lots.

#+BEGIN_SRC emacs-lisp :tangle yes
(setq delete-old-versions -1)
(setq version-control t)
(setq vc-make-backup-files t)
(setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))
#+END_SRC

* History

From http://www.wisdomandwonder.com/wp-content/uploads/2014/03/C3F.html:
#+BEGIN_SRC emacs-lisp :tangle yes
(setq savehist-file "~/.emacs.d/savehist")
(savehist-mode 1)
(setq history-length t)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history 1)
(setq savehist-additional-variables
      '(kill-ring
        search-ring
        regexp-search-ring))
#+END_SRC

* Org Mode
#+BEGIN_SRC emacs-lisp
(setq org-src-fontify-natively t)
#+END_SRC

* remove compilled files
#+BEGIN_SRC emacs-lisp
(defun remove-elc-on-save ()
  "If you're saving an elisp file, likely the .elc is no longer valid."
  (add-hook 'after-save-hook
            (lambda ()
              (if (file-exists-p (concat buffer-file-name "c"))
                  (delete-file (concat buffer-file-name "c"))))
            nil
            t))

(add-hook 'emacs-lisp-mode-hook 'remove-elc-on-save)
#+END_SRC

* doom theme
#+BEGIN_SRC emacs-lisp
(use-package doom-themes
  :ensure t
  :init
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  )
;; Load the theme (doom-one, doom-molokai, etc); keep in mind that each theme
;; may have their own settings.
(load-theme 'doom-peacock t)

;; Enable flashing mode-line on errors
(doom-themes-visual-bell-config)

;; Enable custom neotree theme
(doom-themes-neotree-config)  ; all-the-icons fonts must be installed!

;; Corrects (and improves) org-mode's native fontification.
(doom-themes-org-config)
#+END_SRC

* cuda package
#+BEGIN_SRC emacs-lisp
(use-package cuda-mode
  :ensure t
)
#+END_SRC

* auto complete
#+BEGIN_SRC emacs-lisp
(use-package auto-complete
  :ensure t)
#+END_SRC
Dont pay attention to image files and compiled files
#+BEGIN_SRC emacs-lisp
;https://stackoverflow.com/a/43204202
(setq completion-ignored-extensions
    (append completion-ignored-extensions
        (quote
        (".tif" ".png" ".jpg" ".pyc" ".so" ".gif"))))
#+END_SRC
* Pdf viewing
#+BEGIN_SRC emacs-lisp
(setq doc-view-ghostscript-program "/usr/local/bin/gs")

#+END_SRC
#+BEGIN_SRC emacs-lisp :tangle no
;;; https://emacs.stackexchange.com/a/22591
;;; Install epdfinfo via 'brew install pdf-tools' and then install the
;;; pdf-tools elisp via the use-package below. To upgrade the epdfinfo
;;; server, just do 'brew upgrade pdf-tools' prior to upgrading to newest
;;; pdf-tools package using Emacs package system. If things get messed
;;; up, just do 'brew uninstall pdf-tools', wipe out the elpa
;;; pdf-tools package and reinstall both as at the start.
(use-package pdf-tools
  :ensure t
  :config
  (custom-set-variables
    '(pdf-tools-handle-upgrades nil)) ; Use brew upgrade pdf-tools instead.
  (setq pdf-info-epdfinfo-program "/Applications/Skim.app/Contents/MacOS/Skim"));;"/usr/local/bin/epdfinfo"))
(pdf-tools-install)
#+END_SRC
* fly check
#+BEGIN_SRC emacs-lisp
;; fly-check
(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))

(add-hook 'after-init-hook 'global-flycheck-mode)
#+END_SRC

* ido mode
#+BEGIN_SRC emacs-lisp
; Use ido
(require 'ido)
(ido-mode 1)

(setq ido-enable-flex-matching t)
(setq ido-everywhere t)
(setq ido-use-filename-at-point 'guess)
(setq ido-file-extensions-order '(".org" ".txt" ".py"))
#+END_SRC

* hooks
#+BEGIN_SRC emacs-lisp
(add-hook 'LaTeX-mode-hook 'flyspell-mode)
(setq linum-format "%d ")
#+END_SRC

* key bindings
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-c") 'comment-region)
(global-set-key (kbd "M-u") 'uncomment-region)
#+END_SRC

* interactive python mode
#+BEGIN_SRC emacs-lisp
(use-package ein
  :ensure t
  :init
  (setq ein:use-auto-complete t;auto-complete commands
        ein:use-smartrep t;repeating without bindings 
        ))
#+END_SRC
Setup
#+BEGIN_SRC emacs-lisp
(require 'ein)
(require 'ein-loaddefs)
(require 'ein-notebook)
(require 'ein-subpackages)
#+END_SRC

* Babel Org Mode
This is where extra languages are loaded in
#+BEGIN_SRC emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((ipython . t)
   ;; other languages..
   ))
(setq org-confirm-babel-evaluate nil)
;(add-hook ‘org-babel-after-execute-hook ‘org-display-inline-images ‘append)
#+END_SRC

* org ipython
#+BEGIN_SRC emacs-lisp
(use-package ob-ipython
  :ensure t
)
#+END_SRC
* smartrep
#+BEGIN_SRC emacs-lisp
(use-package smartrep
  :ensure t)
#+END_SRC

Changing Window size tends to execute the same command continuously. It is boring work. So eval this example and type =C-x { { {=
#+BEGIN_SRC emacs-lisp
(smartrep-define-key
    global-map "C-x"
  '(("{" . shrink-window-horizontally)
    ("}" . enlarge-window-horizontally)))

#+END_SRC


* tangle init automatically
#+BEGIN_SRC emacs-lisp :tangle yes 
 (use-package async 
  :ensure t
  :config
   (defun my/init-hook ()
     "If the current buffer is 'settings.org' the code-blocks are tangled."
     (when (equal (buffer-file-name) (expand-file-name "~/config/settings.org"))
      (async-start
       `(lambda ()
          (require 'org)
          (org-babel-tangle-file (expand-file-name "~/config/settings.org") (expand-file-name "~/config/settings.el")))
       (lambda (result)
         (message "Tangled file compiled."))))))

  (add-hook 'after-save-hook 'my/init-hook nil) 
 ; (add-hook 'after-save-hook 'byte-compile-file (expand-file-name "~/config/settings.el"))
#+END_SRC

* user info
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Corey D Smith")
(setq user-mail-address "coreys@uchicago.edu") 
#+END_SRC

** yes no
#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
